### ISSUE TITLE
Changing the delimiter causes inventory import to break

### ISSUE THREAD

**Issue by amenk** [techdivision/import-product-msi#8]
We need to set

    "multiple-field-delimiter" : "¦",
    "multiple-value-delimiter" : "|"

because we believe otherwise the configurable import will break on attributes that contain `,` (the standard field-delimiter)

This change seems to cause the following error

     Can't load inventory source with code "default¦status" in file inventory-msi_20200629_2.csv on line 2 

Lower prio for us, as we basically can disable MSI I hope.

**Comment by amenk** [comment]
Okay, it is not a good idea to use a unicode character as delimiter, because the \TechDivision\Import\Subjects\SubjectInterface::explode function works with fgetcsv which does not support unicode as delimiters.

This whole CSV-in-CSV-in-CSV stuff for the expression of configurables is really a mess in Magento :)

**Comment by wagnert** [comment]
Hi @amenk, indeed the csv-in-csv-in-csv is kinda weird and not easy to handle in some cases. Probably we have got the chance to add an XML alternative soon 🙂
